const affirmations = [
  {affirmation: "I am succeeding in life"},
  {affirmation: "I know I can achieve anything I want in life"},
  {affirmation: "Prosperity flows to and through me"},
  {affirmation: "I will succeed by attracting people who can help me"},
  {affirmation: "I know a positive attitude can bring me success"},
  {affirmation: "I am happy with who I am and can be"},
  {affirmation: "Today I am going to bid farewell to old bad habits and welcome a positive change in my life"},
  {affirmation: "I am worthy enough to follow my dreams and manifest my desires"},
  {affirmation: "I can achieve what I have dreamt for myself"},
  {affirmation: "I am harder than all the challenges and hurdles lying in my way"},
  {affirmation: "I am blessed to have everything in my life to make it successful"},
  {affirmation: "I am capable of attracting daily abundance"},
  {affirmation: "I am attuned to the abundance of success"},
  {affirmation: "I celebrate the abundance of everything in my life"},
  {affirmation: "I believe in myself"},
  {affirmation: "I am open to receiving unexpected opportunities"},
  {affirmation: "I choose to embrace the mystery of life"},
  {affirmation: "I am my best source of motivation"},
  {affirmation: "I am capable of achieving greatness"},
  {affirmation: "I am grateful for the abundance that I have and the abundance that is on its way"},
  {affirmation: "I attract miracles into my life"},
  {affirmation: "I achieve whatever I set my mind to"},
  {affirmation: "I am open to limitless possibilities"},
  {affirmation: "I am a strong individual who attracts success and happiness"},
  {affirmation: "I let go of old, negative beliefs that have stood in the way of my success"},
  {affirmation: "The world needs my light and I am not afraid to shine"},
  {affirmation: "Every day I become more confident"},
  {affirmation: "I am worthy of all the good life has to offer"},
  {affirmation: "I create the life I want and enjoy it"},
  {affirmation: "I am surrounded by positive people who believe in me"},
  {affirmation: "I stay focused on my vision and pursue my daily work with passion"},
  {affirmation: "I take pride in my ability to make worthwhile contributions to the world"},
  {affirmation: "Everywhere I look I see prosperity"},
  {affirmation: "Wealth constantly flows into my life"},
  {affirmation: "I am living my life in a state of complete abundance"},
  {affirmation: "I believe that I can do anything."},
  {affirmation: "I have goals and dreams that I am going to achieve"},
  {affirmation: "I am a goal getter and will not stop at anything to achieve my goals"},
  {affirmation: "I am committed to achieving success in every area of my life"},
  {affirmation: "I choose positivity"},
  {affirmation: "I am worthy of my dream job and am creating the career of my dreams"},
  {affirmation: "I believe in me"},
  {affirmation: "I easily accomplish all of my goals"},
  {affirmation: "I am enough"},  
  
];

export default affirmations;
